server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: catalog-service
              uri: http://catalog-service:8080
              predicates:
                - Path=/api/books/**

            - id: authoring-service
              uri: http://authoring-service:8080
              predicates:
                - Path=/api/authoring/**

            - id: author-service
              uri: http://author-service:8080
              predicates:
                - Path=/api/user/**

            - id: user-service
              uri: http://user-service:8080
              predicates:
                - Path=/api/user/**

            - id: authoring-service-api-docs
              uri: http://authoring-service:8080
              predicates:
                - Path=/aggregate/authoring-service/api-docs
              filters:
                - RewritePath=/aggregate/authoring-service/api-docs, /api-docs

            - id: catalog-service-api-docs
              uri: http://catalog-service:8080
              predicates:
                - Path=/aggregate/catalog-service/api-docs
              filters:
                - RewritePath=/aggregate/catalog-service/api-docs, /api-docs

            - id: user-service-api-docs
              uri: http://user-service:8080
              predicates:
                - Path=/aggregate/user-service/api-docs
              filters:
                - RewritePath=/aggregate/user-service/api-docs, /api-docs
                
            - id: author-service-api-docs
              uri: http://author-service:8080
              predicates:
                - Path=/aggregate/author-service/api-docs
              filters:
                - RewritePath=/aggregate/author-service/api-docs, /api-docs

          globalcors:
            cors-configurations:
              "[/**]":
                allowedOrigins: "http://localhost:4200"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                  - PATCH
                allowedHeaders: "*"
                allowCredentials: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Authoring Service
        url: /aggregate/authoring-service/api-docs
      - name: Catalog Service
        url: /aggregate/catalog-service/api-docs
      - name: Author Service
        url: /aggregate/author-service/api-docs
      - name: User service
        url: /aggregate/user-service/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
